### PR TITLE
Fixes to compile on linux

### PR DESCRIPTION
**Pull request by oyvindln**
Compiled on Ubuntu 18.04 with these changes, so I thought you might be interested. I don't see any reason why they should cause any issues on windows.

### CODE REVIEW

**Review by KeldorKatarn — CHANGES_REQUESTED** [review]
Most of the changes I can do. But this I won't do:

../stdafx.h

That is incredibly bad code and it's bad enough this happens all over the place in this project. The base directory of a code base ALWAYS has to be an include directory. with this crappy relative directory stuff it's impossible to move a file around. The path would no longer work.
Instead please adjust the linux project/makefile whatever  the linux compiler needs to regard the src directory an include directory.
That's the proper fix for that.

**Comment by oyvindln** [comment]
That's what's in the [official repository](https://github.com/OpenTTD/OpenTTD/blob/master/src/linkgraph/linkgraphschedule.cpp#L12), though I agree it's a rather clunky way of doing things. I'll see if I can fix the build system settings to deal with it.

**Comment by KeldorKatarn** [comment]
Oh I know it's in the main repository. but I don't want to continue that trend. I already got rid of some of that stuff. There's lots of bad stuff in the main repository. if you can fix this to get those headers properly included I'll pull the request.

**Comment by oyvindln** [comment]
Okay, I've added the source directory as an include directory (and reverted the `../include`s since they're no longer needed.

**Comment by KeldorKatarn** [comment]
Btw please make pull requests against development, not master.

**Comment by oyvindln** [comment]
Will do next time.

**Comment by KeldorKatarn** [comment]
No worries, I moved the commit to development.

**Pull request merged**
